run:
  # timeout for analysis
  deadline: 4m

  # Linting uses a lot of memory. Keep it under control by only running a single
  # worker.
  concurrency: 1

linters-settings:
  gofmt:
    # simplify code: gofmt with `-s` option, true by default
    simplify: true

linters:
  enable-all: true
  disable:
  # Global variables are used in many places throughout the code base.
  - gochecknoglobals

  # Some lines are over 80 characters on purpose and we don't want to make them
  # even longer by marking them as 'nolint'.
  - lll

  # We don't care (enough) about misaligned structs to lint that.
  - maligned

  # We have long functions, especially in tests. Moving or renaming those would
  # trigger funlen problems that we may not want to solve at that time.
  - funlen

  # Disable for now as we haven't yet tuned the sensitivity to our codebase
  # yet.  Enabling by default for example, would also force new contributors to
  # potentially extensively refactor code, when they want to smaller change to
  # land.
  - gocyclo

  # Instances of table driven tests that don't pre-allocate shouldn't trigger
  # the linter.
  - prealloc

  # Init functions are used by loggers throughout the codebase.
  - gochecknoinits

issues:
  # Only show newly introduced problems.
  # Note that travis only clones the last 50 commits by default. If the repo
  # progresses to a point where we are >50 commits from this point, travis will
  # fail with exit status 128: "Can't process result by diff processor". To fix
  # this, the commit should be updated to the latest commit. An alternative fix
  # is to remove travis's depth limitation.
  new-from-rev: ac096132b0afaf2abf63061c8112e712cb9fac16
